name: humanoid-ppo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - jupyter
  - pytorch
  - torchvision
  - gym=0.21.0
  - pip
  - pip:
    - stable-baselines3[extra]
    - pybullet==3.1.7
